name: ROS2 CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - galactic
        include:
            # Galactic
          - docker_image: rostooling/setup-ros-docker:ubuntu-focal-ros-galactic-desktop-latest
            ros_distribution: galactic
            ros_version: 2
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: Setup directories
        run: mkdir -p ros_ws/src
      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@0.2.1
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: ""
          target-ros2-distro: ${{ matrix.ros_distribution }}
          # vcs-repo-file-url: "https://raw.githubusercontent.com/spraybot/spraybot/main/spraybot.repos"
          colcon-defaults: |
            {
              "build": {
            "mixin": ["coverage-gcc", "coverage-pytest"]
            },
            "test": {
              "mixin": ["coverage-pytest"]
            }
            }
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/1ddb69bedfd1f04c2f000e95452f7c24a4d6176b/index.yaml
      - name: Code Coverage
        uses: codecov/codecov-action@v2.1.0
        with:
          files: ros_ws/lcov/total_coverage.info,ros_ws/coveragepy/.coverage
          fail_ci_if_error: false
          verbose: true
